# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Tue Oct 14 08:49:01 2025
#

import wx




class _994137015_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((587, 700))
        self.SetTitle("frame_1")
        self.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.SetForegroundColour(wx.Colour(0, 0, 0))

        self.panel_1 = wx.Panel(self, -1)
        self.panel_1.SetMinSize((700, 396))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("D:\\cineplusHector Uriel3A\\1456687.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self.panel_1, -1, "Taquilla", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((200, 30))
        label_1.SetFont(wx.Font(26, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bauhaus 93"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.RESERVE_SPACE_EVEN_IF_HIDDEN, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("D:\\cineplusHector Uriel3A\\1456687.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, -1, "Pelicula:")
        label_2.SetMinSize((150, 50))
        label_2.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_2.Add(label_2, 0, 0, 0)

        self.combo_box_1 = wx.ComboBox(self.panel_1, -1, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_2.Add(self.combo_box_1, 0, wx.ALL, 19)

        bitmap_3 = wx.StaticBitmap(self.panel_1, -1, wx.Bitmap("D:\\cineplusHector Uriel3A\\au_marvel_avengersendgame_hero_m_f8ba68d1.jpeg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_3, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, -1, "Sala 1")
        label_3.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(label_3, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, -1, "Horario")
        label_4.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.radio_btn_1 = wx.RadioButton(self.panel_1, -1, "17:00")
        self.radio_btn_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(self.radio_btn_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.radio_btn_2 = wx.RadioButton(self.panel_1, -1, "18:00")
        self.radio_btn_2.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(self.radio_btn_2, 0, 0, 0)

        self.radio_btn_3 = wx.RadioButton(self.panel_1, -1, "19:00")
        self.radio_btn_3.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_3.Add(self.radio_btn_3, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, -1, "Adultos($80):\n")
        label_5.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_4.Add(label_5, 0, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_CENTRE)
        grid_sizer_4.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, -1, "Menores($70):")
        label_6.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        grid_sizer_5.Add(label_6, 0, 0, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_CENTRE)
        grid_sizer_5.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 0)

        label_7 = wx.StaticText(self.panel_1, -1, "Subtotal:")
        label_7.SetFont(wx.Font(28, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(label_7, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, -1, "Limpiar")
        grid_sizer_6.Add(self.button_1, 0, wx.ALIGN_CENTER, 0)

        self.button_2 = wx.Button(self.panel_1, -1, "Siguiente")
        grid_sizer_6.Add(self.button_2, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

